export const DYORHUB_CONTRACT_ADDRESS =
  '2MCmXsjSXHoQYR6ckg6Af4mhQKDMJMGy6JKh8C4Qpump';
export const DYORHUB_SYMBOL = '$DYORHUB';
export const MIN_TOKEN_HOLDING_FOR_FEED = 100000;
export const MIN_TOKEN_HOLDING_FOR_FOLDERS = 100000;
export const MIN_TOKEN_HOLDING_FOR_EARLY_BUYERS = 250000;

export const MIN_TOKEN_HOLDING_KEY = 'minTokenHolding';
