export const DYORHUB_CONTRACT_ADDRESS =
  '2MCmXsjSXHoQYR6ckg6Af4mhQKDMJMGy6JKh8C4Qpump';
export const DYORHUB_MARKETING_ADDRESS =
  'B5BwurzzkE1c6S4mrbcuenBTA3F7WwCWQP59dtScbsgx';
export const DYORHUB_SYMBOL = '$DYORHUB';
export const MIN_TOKEN_HOLDING_FOR_FEED = 100000;
export const MIN_TOKEN_HOLDING_FOR_FOLDERS = 100000;
export const MIN_TOKEN_HOLDING_FOR_EARLY_BUYERS = 500000;
export const MIN_TOKEN_HOLDING_FOR_TOP_TRADERS = 500000;
export const MIN_TOKEN_HOLDING_FOR_HOLDERS_ANALYSIS = 750000;
export const MIN_TOKEN_HOLDING_FOR_TWITTER_SENTIMENT_ANALYSIS = 500000;
export const MIN_TOKEN_HOLDING_KEY = 'minDyorHubHolding';
export const MIN_TOKEN_HOLDING_FOR_AI_TA = 1000000;
